# Generated by Django 3.2.12 on 2022-03-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0002_auto_20220309_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioupdate',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
