# Generated by Django 3.2.12 on 2022-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0003_alter_bioupdate_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioupdate',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
