# Generated by Django 3.2.12 on 2022-03-10 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MS', '0005_alter_bioupdate_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioupdate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_spending', to=settings.AUTH_USER_MODEL),
        ),
    ]
